// @title Mowsy API
// @version 1.0
// @description A comprehensive API for lawn care and maintenance services
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

package main

import (
	"log"
	"os"

	"mowsy-api/internal/routes"
	"mowsy-api/pkg/database"

	"github.com/gin-gonic/gin"
	// _ "mowsy-api/docs" // This will be generated by swag - commented out for Go 1.20 compatibility
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
	
	// Set Gin to debug mode for local development
	gin.SetMode(gin.DebugMode)

	// Initialize database
	if err := database.InitDB(); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	// Run auto migrations
	if err := database.AutoMigrate(); err != nil {
		log.Fatalf("Failed to run auto migrations: %v", err)
	}

	// Setup routes
	r := routes.SetupRoutes()

	// Get port from environment or use default
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Starting server on port %s", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}